### ISSUE TITLE
RAGScript NoSuchMethodError issue for SLF4J

### ISSUE THREAD

**Issue by phodal** [unit-mesh/chocolate-factory#2]
link: https://youtrack.jetbrains.com/issue/KT-60813/Scripts-NoSuchMethodError-void-org.slf4j.Logger.errorjava.lang.String-java.lang.Object-when-dependency-uses-Slf4j-API

issue:

similar issue with my code:

```
@file:DependsOn("cc.unitmesh:rag-script:0.3.2")

import cc.unitmesh.rag.*

rag {
    embedding = EmbeddingEngine(EngineType.SentenceTransformers)
    embedding.provider.embed(listOf("hello, world"))
}
```

Issue:

```bash
java.lang.NoSuchMethodError: 'void org.slf4j.Logger.info(java.lang.String, java.lang.Object)'
	at ai.djl.util.Platform.detectPlatform(Platform.java:82)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:82)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:66)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:170)
	at cc.unitmesh.cf.STSemantic$Companion.create(STSemantic.kt:68)
	at cc.unitmesh.rag.SentenceTransformersEmbedding.<init>(EmbeddingEngine.kt:20)
	at cc.unitmesh.rag.Store.<init>(Workflow.kt:99)
	at cc.unitmesh.rag.Workflow.<init>(Workflow.kt:36)
	at cc.unitmesh.rag.WorkflowKt.rag(Workflow.kt:136)
	at Document_example_main.<init>(document-example.main.kts:5)
```

**Comment by phodal** [comment]
will fixed in  2.0.0-dev-7376
